# Site setings
name: 'Miroslav Bartoš'
description: 'Just a developer'
meta_description: 'CV of Miroslav Bartoš'
logo:
# Author image is used in site sidebar and greetings in the home page hero text
author:
  image: 'author-avatar.png'
  greetings: "Jsem Miroslav Bartoš. Pracuji jako vývojář a toto je především moje veřejné CV."
favicon: 'assets/images/favicon.ico'
baseurl: 
disqus: 'miroslavbartos'

# Contact form setings
email: bartos.store@gmail.com
contact_page_description: "Ask me a question."
thankyou_page_description: "Your message has been successfully sent."

# Social links
facebook: 'miroslav.bartos.39'
twitter: 'BartosMiroslav'
github: 'BartosStore'
linkedin: 'miroslav-bartoš-6a197b185'

# Navigation
navigation:
 - text: Home
   url: /
 - text: CV
   url: /tag/cv/
 - text: Vývoj
   url: /tag/development/   
 - text: Knihy
   url: /tag/book/
 - text: Auta
   url: /tag/car/   
 - text: Rum
   url: /tag/rum/
 - text: Kontakt
   url: /contact/

# Required Plugins
plugins_dir:
  - jekyll-paginate
  - jekyll-tagsgenerator
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-gist

# Pagination
paginate: 5
paginate_path: /page:num/

excerpt_link: "Read on &rarr;"  # "Continue reading" link text at the bottom of excerpted articles
excerpt_separator: "<!-- more -->"

# Permalinks
permalink: "/blog/:year/:month/:day/:title/"

# Other
markdown: kramdown

# Sass
sass:
  sass_dir: _sass
  style: compressed
